"""increase character limit for explanations

Revision ID: 1f537e4b0f73
Revises: 
Create Date: 2024-03-05 07:53:02.452802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f537e4b0f73'
down_revision = None
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanation', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.drop_constraint('fk_explanation_scenario_id_scenario', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'scenario', ['scenario_id'], ['id'])
        batch_op.alter_column('reason',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
