"""ind bonus for each selection

Revision ID: 23da03f4d9ba
Revises: 4ac1b3322337
Create Date: 2024-03-03 01:24:01.125211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23da03f4d9ba'
down_revision = '4ac1b3322337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('num_selections', sa.Integer(), nullable=True))
        batch_op.drop_column('total_error')

    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_b', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.drop_column('bonus_b')
        batch_op.drop_column('bonus_a')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_error', sa.INTEGER(), nullable=True))
        batch_op.drop_column('num_selections')
        batch_op.drop_column('bonus')
        batch_op.drop_column('error')

    # ### end Alembic commands ###
