"""added individual errors to each selection

Revision ID: 4ac1b3322337
Revises: 4fa0fa15f2d6
Create Date: 2024-03-02 11:45:33.080306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac1b3322337'
down_revision = '4fa0fa15f2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_b', sa.Integer(), nullable=True))
        batch_op.drop_column('error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.INTEGER(), nullable=True))
        batch_op.drop_column('error_b')
        batch_op.drop_column('error_a')

    # ### end Alembic commands ###
