"""error is now integer not float

Revision ID: 903b073e92c7
Revises: 74f9b69dc3d6
Create Date: 2024-02-26 21:02:53.974508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903b073e92c7'
down_revision = '74f9b69dc3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('total_error',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.alter_column('error',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.alter_column('error',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('total_error',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
