"""added optimal filing ages

Revision ID: ad17e3ad209a
Revises: 903b073e92c7
Create Date: 2024-02-26 21:12:02.320397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad17e3ad209a'
down_revision = '903b073e92c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimal_age_a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('optimal_age_b', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('optimal_age_b')
        batch_op.drop_column('optimal_age_a')

    # ### end Alembic commands ###
