"""initial migration

Revision ID: b6b2dfe3a998
Revises: 
Create Date: 2024-02-25 22:58:19.578492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b2dfe3a998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('pia_a', sa.Integer(), nullable=True),
    sa.Column('gender_a', sa.String(length=20), nullable=True),
    sa.Column('current_age_a', sa.Integer(), nullable=True),
    sa.Column('life_expectancy_a', sa.Integer(), nullable=True),
    sa.Column('pia_b', sa.Integer(), nullable=True),
    sa.Column('gender_b', sa.String(length=20), nullable=True),
    sa.Column('current_age_b', sa.Integer(), nullable=True),
    sa.Column('life_expectancy_b', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('mturk_id', sa.String(length=20), nullable=False),
    sa.Column('experiment_completed', sa.Boolean(), nullable=True),
    sa.Column('failed_attention_checks', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('completion_code', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('mturk_id'),
    sa.UniqueConstraint('mturk_id')
    )
    op.create_table('explanation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('num_scenarios', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('selection_a', sa.Integer(), nullable=True),
    sa.Column('selection_b', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection')
    op.drop_table('survey')
    op.drop_table('section')
    op.drop_table('explanation')
    op.drop_table('user')
    op.drop_table('scenario')
    # ### end Alembic commands ###
