"""Clean database migration

Revision ID: dcc7e0574703
Revises: 
Create Date: 2023-09-18 03:54:30.015121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc7e0574703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('moves', sa.String(length=20), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('mturk_id', sa.String(length=20), nullable=False),
    sa.Column('experiment_completed', sa.Boolean(), nullable=True),
    sa.Column('failed_attention_checks', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('completion_code', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('mturk_id'),
    sa.UniqueConstraint('mturk_id')
    )
    op.create_table('explanation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('move_num', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('mistake', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('successes', sa.Integer(), nullable=True),
    sa.Column('num_puzzles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('move_num', sa.Integer(), nullable=True),
    sa.Column('move', sa.String(length=5), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mistake', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    op.drop_table('survey')
    op.drop_table('section')
    op.drop_table('explanation')
    op.drop_table('user')
    op.drop_table('puzzle')
    # ### end Alembic commands ###
